### PR TITLE
fix power armor gui crash

### PR DESCRIPTION
**Pull request by Cordina90**

### CODE REVIEW

**Comment by jokru** [comment]
I'm not sure if this is because of the fix, but I seem to be unable to select lanes, with your fix installed. This means that I can't use anything above the yellow sorter.

**Comment by Cordina90** [comment]
Not being able to select lanes is a different issue. Without this fix I cannot change lanes either. This fix onlusten solves the issue with the power armor gui, the lanes (for avarage and advanced sorters) require charges in the controlscripts (I guess), but I’m no scripter...

**Comment by D-Chase-H** [comment]
@Cordina90 
Thank you for making these fixes.

**Comment by judos** [comment]
Hi there,
Thanks all for checking these issues. I see these changes are already in the 0.6.0 version which I just updated here in the source. So I can close the PR. I will check the lanes issue asap.

**Pull request closed without merging**
